In [1]:
import xarray as xr
import pandas as pd
from pathlib import Path

paths_dataset = list(Path('data/datasets').glob('tabzilla_*.nc'))


dss = [xr.open_dataset(path) for path in paths_dataset]

metadata = []

for ds in dss:

    metadata.append({
        'openml_dataset_id': ds.attrs['openml_dataset_id'],
        'openml_dataset_name': ds.attrs['openml_dataset_name'],
        'n_observations': ds.sizes['observation'],
        'n_features': ds.sizes['feature'],
        'n_splits': ds.sizes['split'],
        'n_train': ds['split_index_train'].sel(split=0).sum().item(),
        'n_val': ds['split_index_val'].sel(split=0).sum().item(),
        'n_test': ds['split_index_test'].sel(split=0).sum().item(),
    })
metadata = pd.DataFrame(metadata)
metadata.set_index('openml_dataset_id', inplace=True)
metadata.sort_index(inplace=True)
metadata

,openml_dataset_name,n_observations,n_features,n_splits,n_train,n_val,n_test
openml_dataset_id,,,,,,,
7,audiology,226,69,10,180,23,23
10,lymph,148,18,10,118,15,15
11,balance-scale,625,4,10,499,63,63
14,mfeat-fourier,2000,76,10,1600,200,200
22,mfeat-zernike,2000,47,10,1600,200,200
25,colic,368,26,10,294,37,37
29,credit-approval,690,15,10,552,69,69
31,credit-g,1000,20,10,800,100,100
45,splice,3190,60,10,2552,319,319
50,heart-h,294,13,10,234,30,30
53,vehicle,846,18,10,676,85,85
219,electricity,45312,8,10,36248,4532,4532
3561,profb,672,9,10,536,68,68
3711,elevators,16599,18,10,13279,1660,1660
3797,socmob,1156,5,10,924,116,116
3896,ada_agnostic,4562,48,10,3648,457,457
3917,kc1,2109,21,10,1687,211,211
9890,poker-hand,1025009,10,10,820007,102501,102501
9910,Bioresponse,3751,1776,10,3000,375,376
9952,phoneme,5404,5,10,4322,541,541
9956,one-hundred-plants-texture,1599,64,10,1279,160,160
9957,qsar-biodeg,1055,41,10,843,106,106
9977,nomao,34465,118,10,27571,3447,3447
9981,cnae-9,1080,856,10,864,108,108
14964,artificial-characters,10218,7,10,8174,1022,1022
14969,GesturePhaseSegmentationProcessed,9873,32,10,7897,988,988
146065,monks-problems-2,601,6,10,480,60,61
146606,higgs,98050,28,10,78440,9805,9805
146607,SpeedDating,8378,120,10,6702,838,838
146818,Australian,690,14,10,552,69,69
167119,jungle_chess_2pcs_raw_endgame_complete,44819,6,10,35855,4482,4482
168335,MiniBooNE,130064,50,10,104050,13007,13007
168337,guillermo,20000,4296,10,16000,2000,2000
168911,jasmine,2984,144,10,2386,299,299
189354,airlines,539383,7,10,431505,53939,53939
189356,albert,425240,78,10,340192,42524,42524